# 安装ollama
install-ollama:
	@echo "Installing ollama..."
	@bash -c "brew install ollama"
# 安装pyenv 一个python版本管理工具
install-python:
	@echo "Installing pyenv..."
	@bash -c "brew install pyenv"

# 安装python3.9
install-python3.9:
	@echo "Installing Python 3.9..."
	@bash -c "pyenv install 3.9.5"

#进入虚拟空间
virtual:
	@echo "Activating virtual environment..."
	@bash -c "source rag-env/bin/activate"

# 安装依赖
install:
	@echo "Installing dependencies..."
	@bash -c "pip install -r requirements.txt"

# 下载sentence-transformers模型
download-model:
	@echo "Downloading sentence-transformers model..."
	@bash -c "/usr/local/bin/python3.9 download_model.py"

# 更新知识库
update:
	@echo "Updating documentation..."
	@bash -c "/usr/local/bin/python3.9 ingest.py"

# 更新角色列表
update-roles:
	@echo "Updating roles..."
	@bash -c "/usr/local/bin/python3.9 extract_roles.py"

# 运行程序
run:
	@echo "Activating virtual environment..."
	@bash -c "/usr/local/bin/python3.9 rag.py"